### ISSUE TITLE
Test the model on randomly selected engine from the test dataset

### ISSUE THREAD

**Issue by yukino994** [abiodun-ayodeji/Attention_based_MultiHead_model_for_aircraft_engine_RUL_prediction_#2]
Hello！
eng_df = pd.read_csv(
        "/content/sample_data/Eng_plot_" + str(numb) + "_" + filename + ".csv"
    )
There is no "/content/sample_data/Eng_plot_" + str(numb) + "_" + filename + ".csv" files.
Could you help me?

**Comment by abiodun-ayodeji** [comment]
Hi. You should replace the path with your own path (i.e. where you downloaded the data). I hope this helps.

**Comment by abiodun-ayodeji** [comment]
> Quote reply
